# -*- coding: utf-8 -*-
"""NLP Spam Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYQ1IuHmigEhXhZhRzpPzJOZ6xQ-ve0P

# **Spam Detection**
"""

# Acquire spam dataset from Kaggle

# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "spam.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "uciml/sms-spam-collection-dataset",
  file_path,
  pandas_kwargs={'encoding': 'latin-1'}
)

print("First 5 records:", df.head())

# Text cleaning and normalization

import re

# Drop unused columns, rename v1 as 'label' (spam/ham) and v2 as 'text'

# Check if 'Unnamed' columns exist before dropping
columns_to_drop = [col for col in ["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"] if col in df.columns]
if columns_to_drop:
    df = df.drop(columns_to_drop, axis=1)
df = df.rename(columns={"v1": "label", "v2": "text"})

# Lowercase
df['text'] = df['text'].str.lower()

# URLs
df['text'] = df['text'].apply(lambda x: re.sub(r'http\S+', 'URL', x))

# TF - IDF (unigram tokenization) and split 80-20

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state=42, stratify=df['label'])
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(x_train)
X_test = vectorizer.transform(x_test)

# Train

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

lg = LogisticRegression(max_iter=1000)
lg.fit(X_train, y_train)
# nb = MultinomialNB()
# nb.fit(x_train, y_train)
y_pred = lg.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))